=== JoseJulioLopezValero/lenguaje-de-marcas/tema1-xml/Lopez_Valero_JoseJulio_LM_U1_T2_DTD/Ejercicio5Externa.dtd
<!ELEMENT discos (titulo, interprete+, pistas+)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT interprete (nombre, apellidos, rol)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT rol (#PCDATA)>
    <!ELEMENT pistas (nombre_cancion, duracion)>
    <!ELEMENT nombre_cancion (#PCDATA)>
    <!ELEMENT duracion (#PCDATA)>

=== JoseJulioLopezValero/lenguaje-de-marcas/tema1-xml/Lopez_Valero_JoseJulio_LM_U1_T2_DTD/Ejercicio5Externa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE discos SYSTEM "Ejercicio5Externa.dtd"> 

<discos>
    <titulo>Du Hast</titulo>
    <interprete>
        <nombre>Till</nombre>
        <apellidos>Lindemann</apellidos>
        <rol>solista</rol>
    </interprete>
    <interprete>
        <nombre>Richard</nombre>
        <apellidos>Kruspe</apellidos>
        <rol>Guitarra lider</rol>
    </interprete>
    <pistas>
        <nombre_cancion>Mutter</nombre_cancion>
        <duracion>4:29</duracion>
    </pistas>
    <pistas>
        <nombre_cancion>Ich will</nombre_cancion>
        <duracion>3:37</duracion>
    </pistas>
</discos>
